mqtt_ros_bridge:
  ros__parameters:
    turtle_pub: 
      topic: "/turtle1/cmd_vel"
      type: "geometry_msgs.msg:Twist"
      publish_on_ros: True

    yippee: 
      topic: "foo"
      type: "std_msgs.msg:String"
      publish_on_ros: True
      use_ros_serializer: True