mqtt_ros_bridge:
  ros__parameters:
    turtle_pub: 
      topic: "/turtle1/cmd_vel"
      type: "geometry_msgs.msg:Twist"
      interaction_type: "ros_subscriber"
    
    # server: 
    #   topic: "serverice"
    #   type: "std_msgs.msg:String"
    #   publish_or_client_on_ros: True
    #   is_service: True

    yippee: 
      topic: "foo"
      type: "std_msgs.msg:String"
      interaction_type: "ros_subscriber"
      use_ros_serializer: True